name: cud_application_project
description: A Flutter project for the CUD Social App.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.8.0
  firebase_auth: ^4.16.0  # Ensure this version is correct
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.2.0
  provider: ^6.0.0
