// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrGWZ4gOcWKPkc6qxGkdI6m101QOmRmpM',
    appId: '1:88413613202:web:aca29cda20c644ad74ca4b',
    messagingSenderId: '88413613202',
    projectId: 'cud-social-app',
    authDomain: 'cud-social-app.firebaseapp.com',
    storageBucket: 'cud-social-app.appspot.com',
    measurementId: 'G-Q00NWPSB1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqZ9F0VmNPngMSXMHP6QJc6d3zH0Y7qzo',
    appId: '1:88413613202:android:61c22f1718cd9cf674ca4b',
    messagingSenderId: '88413613202',
    projectId: 'cud-social-app',
    storageBucket: 'cud-social-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTyMe3D_kf6jqzNi71ZIueIYeKL-55Hw0',
    appId: '1:88413613202:ios:b82608a039d042f174ca4b',
    messagingSenderId: '88413613202',
    projectId: 'cud-social-app',
    storageBucket: 'cud-social-app.appspot.com',
    iosBundleId: 'com.example.cudApplicationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTyMe3D_kf6jqzNi71ZIueIYeKL-55Hw0',
    appId: '1:88413613202:ios:b82608a039d042f174ca4b',
    messagingSenderId: '88413613202',
    projectId: 'cud-social-app',
    storageBucket: 'cud-social-app.appspot.com',
    iosBundleId: 'com.example.cudApplicationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrGWZ4gOcWKPkc6qxGkdI6m101QOmRmpM',
    appId: '1:88413613202:web:ee1b7aac0d316bf574ca4b',
    messagingSenderId: '88413613202',
    projectId: 'cud-social-app',
    authDomain: 'cud-social-app.firebaseapp.com',
    storageBucket: 'cud-social-app.appspot.com',
    measurementId: 'G-039ZB5E383',
  );
}
